api_gw_authenticator:
    defaults:
        env: acceptance # Available values are: acceptance, intra, production

security:
    providers:
        apigwauthenticator:
            id: apigwauthenticator.userprovider
